#!/bin/bash

if [ "$1" ]; then
  if [ "$1" != 'prod' ]; then
    echo "Did you mean 'prod'?"
    exit;
  fi
fi

# install dependencies
echo ""
echo "Installing Dependencies"
echo "---"
npm install
bundle install
echo "---"

if [ "$1" = 'prod' ]; then
  echo ""
  echo "Building Site"
  echo "---"
  bundle exec jekyll build \
  --config 'src/_config.yml,src/_config-production.yml' \
  --source src/ \
  --destination dist/
  echo '---'
  exit
fi

echo ""
echo "Running Development Server"
echo "---"
trap 'echo "Development Server Killed"; kill %1; kill %2; kill %3;' SIGINT SIGKILL SIGQUIT

npx netlify-cms-proxy-server \
& bundle exec jekyll serve \
  --drafts \
  --watch \
  --config 'src/_config.yml,src/_config-development.yml' \
  --source src/ \
& npx browser-sync start -w --proxy=http://localhost:4000 -f ./src --no-open
