backend:
  name: github
  repo: DancingLightStudios/dancinglightstudios.github.io # github path to repo
  site_domain: dancinglightstudios.ca # site name
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

publish_mode: editorial_workflow
media_folder: "src/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # Staff ----------------------------------------------------------------------
  - label: Staff Members
    name: staff-members
    folder: src/_staff_members
    slug: "{{name}}"
    create: true
    fields:
      - label: Full Name
        name: name
        widget: string
      - label: Email
        name: email
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
        required: false
      - label: Bio
        name: body
        widget: markdown
        required: false
  # Job Postings ----------------------------------------------------------------
  - label: Careers
    name: careers
    folder: src/_careers
    slug: "{{title}}"
    create: true
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: default
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
        required: false

  # News Posts -----------------------------------------------------------------
  - label: "News"
    name: "post"
    folder: "src/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: relation
        collection: staff
        search_fields: [name, email]
        value_field: name
      - label: Published
        name: published
        widget: boolean
        required: false
      - label: Date
        name: date
        widget: date
      - label: Categories
        name: categories
        widget: list
        collapsed: false
        fields:
          - label: Category
            name: category
            widget: string
            required: false
      - label: Tags
        name: tags
        widget: list
        collapsed: false
        fields:
          - label: Tag
            name: tag
            widget: string
            required: false
      - label: Hero Image
        name: hero-image
        widget: object
        collapsed: false
        fields:
          - label: Image
            name: src
            widget: image
            required: false
          - label: Alt text
            name: alt
            widget: string
            required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false

  # Site Navigation ------------------------------------------------------------
  - label: Navigation
    name: navigation
    editor:
      preview: false
    files:
      # Main Navigation --------------------------------------------------------
      - label: Site Nav
        name: site-nav
        file: src/_data/site-nav.yml
        fields:
          - label: site-nav-items
            name: items
            widget: list
            allow_add: true
            fields:
              - label: Text
                name: text
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Class
                name: class
                widget: string
                required: false
      # Home Page Navigation ---------------------------------------------------
      - label: Site Nav for Home Page
        name: site-nav-home
        file: src/_data/site-nav-home.yml
        fields:
          - label: site-nav-items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - label: Text
                name: text
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Class
                name: class
                widget: string
                required: false
      # Footer Navigation ------------------------------------------------------
      - label: Footer Navgation
        name: footer-nav
        file: src/_data/footer-nav.yml
        fields:
          - label: Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - label: Text
                name: text
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Class
                name: class
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
              - label: Show Text
                name: show-text
                widget: boolean
                default: true
  # Settings --------------------------------------------------------------------
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      # Site Settings -----------------------------------------------------------
      - label: Site
        name: site
        file: src/_data/constants-site.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Title Safe
            name: title-safe
            widget: string
          - label: Title Abbreviation
            name: title-abbr
            widget: string
          - label: Title Delimiter
            name: title-delimiter
            widget: string
            default: " • "
          - label: Tagline
            name: tagline
            widget: string
          - label: Copyright
            name: copyright
            widget: string
          - label: Site Logo
            name: site-logo
            widget: string
            default: /assets/site-logo.svg
          - label: Site Keywords
            name: site-keywords
            widget: text
            required: false
          - label: Site Description
            name: site-description
            widget: text
            required: false
          - label: Site Contact Email
            name: webmaster
            widget: string

      # Contact Settings --------------------------------------------------------
      - label: Contact
        name: contact
        file: src/_data/constants-contact.yml
        fields:
          - label: email
            name: email
            widget: string
          - label: Phone
            name: phone
            widget: object
            collapsed: false
            fields:
              - label: Phone Number Formatted
                name: Display
                widget: string
              - label: Phone Number without formatting
                name: value
                widget: string
          - label: Address
            name: address
            widget: object
            collapsed: false
            fields:
              - label: Street Address
                name: street
                widget: string
              - label: City
                name: city
                widget: string
              - label: State
                name: state
                widget: string
              - label: Country
                name: country
                widget: string
              - label: Postal Code
                name: postal-code
                widget: string

  # Pages -----------------------------------------------------------------------
  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home
        name: home
        file: src/_data/page-home.yml
        fields:
          - label: Hero Title
            name: hero-title
            widget: string
          - label: Hero Leader
            name: hero-leader
            widget: text
          # Physical Literacy ---------------------------------------------------
          - label: PL Title
            name: pl-title
            widget: string
          - label: PL Leader
            name: pl-leader
            widget: string
          - label: PL Text
            name: pl-text
            widget: text
          - label: PL Points
            name: pl-points
            widget: list
            summary: "{{fields.title}}"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: string
              - label: Icon
                name: icon
                widget: string
          - label: PL Image
            name: pl-image
            widget: object
            collapsed: false
            fields:
              - label: Alt text
                name: alt
                widget: string
                required: false
              - label: Image
                name: src
                widget: image
          - label: Physical Literacy Link
            name: pl-link
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Link
                name: href
                widget: string
          # Location Based Entertainment ----------------------------------------
          - label: LBE Title
            name: lbe-title
            widget: string
          - label: LBE Leader
            name: lbe-leader
            widget: string
          - label: LBE Text
            name: lbe-text
            widget: text
          - label: LBE Points
            name: lbe-points
            widget: list
            summary: "{{fields.title}}"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: string
              - label: Icon
                name: icon
                widget: string
          - label: LBE Image
            name: lbe-image
            widget: object
            collapsed: false
            fields:
              - label: Alt text
                name: alt
                widget: string
                required: false
              - label: Image
                name: src
                widget: image
          - label: Location Based Entertainment Link
            name: lbe-link
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Link
                name: href
                widget: string
          # About ---------------------------------------------------------------
          - label: About Title
            name: about-title
            widget: string
          - label: About Leader
            name: about-leader
            widget: string
          - label: About Text
            name: about-text
            widget: markdown
          - label: About Images
            name: about-images
            widget: list
            summary: "{{fields.alt}}"
            fields:
              - label: Alt text
                name: alt
                widget: string
                required: false
              - label: Image
                name: src
                widget: image
          - label: About Link
            name: about-link
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Link
                name: href
                widget: string
      # Page Physical Literacy --------------------------------------------------
      - label: Physical Literacy
        name: page-pl
        file: src/_data/page-pl.yml
        fields:
          - label: Header
            name: header
            widget: string
          - label: SubHeader
            name: subheader
            widget: string
          - label: Body
            name: body
            widget: markdown
            required: false
          - label: Images
            name: images
            widget: list
            summary: "{{fields.alt}}"
            fields:
              - label: Alt text
                name: alt
                widget: string
                required: false
              - label: Image
                name: src
                widget: image
      # Page Location Based Entertainment ---------------------------------------
      - label: Location Based Entertainment
        name: page-lbe
        file: src/_data/page-lbe.yml
        fields:
          - label: Header
            name: header
            widget: string
          - label: SubHeader
            name: subheader
            widget: string
          - label: Body
            name: body
            widget: markdown
            required: false
          - label: Images
            name: images
            widget: list
            summary: "{{fields.alt}}"
            fields:
              - label: Alt text
                name: alt
                widget: string
                required: false
              - label: Image
                name: src
                widget: image
      # Page About --------------------------------------------------------------
      - label: About
        name: page-about
        file: src/_data/page-about.yml
        fields:
          - label: Header
            name: header
            widget: string
          - label: SubHeader
            name: subheader
            widget: markdown

          - label: Values
            name: values
            widget: list
            summary: "{{fields.title}}"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: markdown
          - label: Leadership
            name: leadership
            widget: list
            summary: "{{fields.staff}}"
            fields:
              - label: Staff
                name: staff
                widget: relation
                collection: staff
                search_fields: [name]
                value_field: name

      # Page Careers ------------------------------------------------------------
      - label: Careers
        name: page-careers
        file: src/_data/page-careers.yml
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: page
          - label: Title
            name: title
            widget: string
          - label: Hero Image
            name: hero-image
            widget: object
            collapsed: false
            fields:
              - label: Image
                name: src
                widget: image
                required: false
              - label: Alt text
                name: alt
                widget: string
                required: false
          - label: Body
            name: body
            widget: markdown
            required: false
