plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-default-layout
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

# !Build Stuff
markdown:    kramdown
exclude:     [] # Files and folders to skip when building
keep_files:  [] # when clobbering the dest, keep the files
destination: "dist" # Where jekyll will build the site to
permalink:   /:title # how urls will be created. eg: "website.com/category/title"
charset:     utf-8 # Website character set
baseurl:     ""     # root

# Concatenation configuration
css:
  path: assets/css/
  # style: compressed
page_js:
  path: assets/js/
  # minify: true
fonts:
  variable: true
  path: assets/fonts/

kramdown:
  parse_block_html: true

optional_front_matter:
  enabled: true
  remove_originals: true

titles_from_headings:
  enabled: true
  collections: true

pagination:
  enabled: true

relative_links:
  enabled: true
  collections: true

collections:
  staff_members:
  careers:
    output: true

# !- Publishing Information
url: "https://dancinglightstudios.ca" # primary url the website will reside at
creator: "gregdaynes.com" # Name or twitter handle of the website creator
lang: "en-CA" # base language for website
permalink: pretty
title: "Dancing Light Studios" # Title for site - used in jekyll-feed
description: "Dancing Light Studios is poised to revolutionize the realms of education and entertainment through awe-inspiring AR, VR, and MR experiences. Our technology is driven by a passion to empower, engage, and enlighten. The canvas of possibilities is endless, and we’re painting it with pixels of progress. A new era beckons, and Dancing Light Studios is leading the way. Be part of the transformation – because everything is about to change." # Longform description of site
keywords: "Dancing Light Studios, Location Based Entertainment, Phsyical Literacy, Augmented Reality, AR, XR, MR, VR, Immersive Learning" # comma separated words to describe site
ownership: "" # url for rel=me

feed:
  path: /feed.xml

defaults:
  - scope:
      path: 'styleguide/**/*.html'
    values:
      sitemap: false
  - scope:
      path: 'admin/**/*.*'
    values:
      sitemap: false
  - scope:
      path: '_careers/**/*.md'
    values:
      layout: 'career'
      class: career
      css:
        - page-career.css
  - scope:
      path: '_posts/**/*.md'
    values:
      layout: 'spark'
      class: spark
      css:
        - page-campfire.css
      permalink: /campfire/:year/:slug/index.html
